### ISSUE TITLE
Query regarding construction of libraries for annotation

### ISSUE THREAD

**Issue by jphruska** [JBerthelier/PiRATE#10]
Hi Jeremy--

Once again, thanks for constructing PiRATE. I've very much enjoyed using it so far. 

I do have another question, if you don't mind. More like a clarification. I've finished the classification step and have received my output from PASTEC. Now I'm starting to look into the manual check step, and had a question regarding how to proceed. My understanding is that the manual check is only meant to be performed on the autonomous sequences, using MCL and Blastn. In order to do so, is the expectation that one has to pull LTR, LINE and TIR sequences (using PASTEC information) manually and then feed that to MCL and Blastn? If so, was there a script that was used for this purpose, or is the expectation that we write that ourselves? 

Thanks for the clarification.
Best
Jack

**Comment by JBerthelier** [comment]
Hi Jack,

The automatisation of this part will be the major update of the new version of PiRATE.

Yes you have to do it by yourself at now.

The goal of this step is to build your autonomous TE library for the annotation.

- To build your library, you have to do manually :

1 - You have to download the output of PASTEC (.tabular) and open it with a spreadsheet
2 - sort the classified sequences according to their Order (TIR, LTR, MITE,...)
3 - select the names of the sequences belonging to same Order and extract the DNA sequences from the fasta file that you used for the classification. You have to build a fasta file for each Order.
(a fasta file for LTR, a fasta file for LINE, a fatsa file for TIR ...)
You have to do it by yourself with linux--> for exemple http://seqanswers.com/forums/showthread.php?t=50014

4. The manual check with MCL is only to have cluster of TE familly and is optional
Run MCL with each fasta file of each Order of autonomous TEs, you will get cluster of potential familly.  
The purpose of BLASTn is only to check if you are agree with the clustering of MCL.

5. Build you TE library with your the referent TE sequences that are classified (and clutered). 
I advise you to firslty build a TE library containing only the autonomous TEs Order ( LTR, LINE, TIR).

You can build other library contenning autonomous TEs Orders and non-autonomous (SINE, MITE, LARD, TRIM), but the latter are difficult to detcet and classify and need to be carfully regarded.

**Comment by jpicathartes** [comment]
Hi Jeremy--

Another quick question if you don't mind me asking.

My apologies in advance for the naive question, but I've only just begun working on TEs and annotations. I've run putative LINE sequences (according to PASTEC) through MCL, and I am wondering if you would help me interpret the output. What I have received now is the name of the sequences that match specific groups (which I would assume are the clusters?). In addition, the fasta headers are now renamed with the cluster ID they are assigned to. How are these clusters determined? Also, some clusters appear to have way more sequences than others. What would the clusters pertain to, exactly? How can I interpret this output in combination with the BLASTn search that follows?

Many thanks for your time, and again, apologies for the barrage of questions. 

Best
Jack

**Comment by jpicathartes** [comment]
Thanks for the information, Jeremy. 

All the best
Jack
