### ISSUE TITLE
Problem with TEannot 

### ISSUE THREAD

**Issue by ayala-usma** [JBerthelier/PiRATE#11]
Hi!

I have been trying to run TEannot in a genome assembly, and the following error appeared:

```

Fatal error: Exit code 1 ()
ERROR: job '88457', supposedly still running, is not handled by SGE anymore
it was launched the 2018-10-22 19:22:42 (> 1.00 hours ago)
this problem can be due to:
* memory shortage, in that case, decrease the size of your jobs;
* timeout, in that case, decrease the size of your jobs;
* node failure or database error, in that case, launch the program again or ask your system administrator.

```

My genome size is ~270 Mb.

It also reports:

```
There is no job registered for the following users: jeremy
```

Thank you

**Comment by JBerthelier** [comment]
You can also check the state of SGE to be sure that there is not a avorted "job"  which stop the others.

You see if the jobs of TEannot (managed by SGE) is working correctly in tapping "qstat" in the Konsol.

See: http://gridscheduler.sourceforge.net/htmlman/htmlman1/qstat.html

Please let me know what appear when you use "qstat"     (without the ").

You can remove all the job with the command "qstat -u jeremy"

Best,

**Comment by JBerthelier** [comment]
An other point, be careful that your sequences (TE library and Genome) have a size of 60 pb per lines. This is very important for the TEannot work.

Best
