### ISSUE TITLE
GFF output from TE annotation

### ISSUE THREAD

**Issue by lyy005** [JBerthelier/PiRATE#12]
Hi there,
Thank you for providing this package for TE annotation. It's super easy to use so many TE annotation tools. At the same time, I have a quick question about the output of different annotation programs. I found it usually just provide a .fasta file output. I was wondering what would be the best way to retrieve the location information on the genome of TE annotations? For example, is there a gff format output I can easily get from the output? 

Thank you

YY

**Comment by JBerthelier** [comment]
Dear lyy005, 

Thank you for your enthusiasm about PiRATE.

The objectif of PiRATE is to provide a variey of detection tool to identify potential TEs sequences in the studied genome.
With PASTEC you can classify the detected TEs sequences (and remove the false positives).
Finaly, you have to manually build a TE library for the annotation 
(see example : https://github.com/JBerthelier/PiRATE/issues/10) 

The TE annotation can be done with the efficient tool TEannot. 
TEannot will provide you a GFF file as output.

Hope this will help you.

Best regards, 

Jérémy

**Comment by lyy005** [comment]
Thank you Jérémy. This is helpful! 

YY
