### ISSUE TITLE
resize virtual hard disk

### ISSUE THREAD

**Issue by jazberna1** [JBerthelier/PiRATE#15]
Hello,

I was wondering wether it possible to resize the virtual hard disk that is eventually created in the Pirate VM. In my case it the hard disk is limited to 300G. 

I am using Ubuntu Virtual Vox 5.2.18

Many thanks
Jorge

**Comment by jazberna1** [comment]
Hi,

This seems to work for me:

```
/usr/bin/vboxmanage clonemedium -format VDI PiRATE_v1-2-disk1.vmdk PiRATE_v1-2-disk1.vdi
/usr/bin/vboxmanage modifyhd PiRATE_v1-2-disk1.vdi --resize 600000
```

Jorge

**Comment by JBerthelier** [comment]
Hi Jorge, 

Yes, this is the solution. 

Thank you for your message. 

Jeremy 

----- Mail original -----

De: "Jorge Zamora" <notifications@github.com> 
À: "JBerthelier/PiRATE" <PiRATE@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Lundi 1 Avril 2019 09:51:08 
Objet: Re: [JBerthelier/PiRATE] resize virtual hard disk (#15) 



Hi, 

This seems to work for me: 
/usr/bin/vboxmanage clonemedium -format VDI PiRATE_v1-2-disk1.vmdk PiRATE_v1-2-disk1.vdi
/usr/bin/vboxmanage modifyhd PiRATE_v1-2-disk1.vdi --resize 600000 


Jorge
