### ISSUE TITLE
transferring data to vm

### ISSUE THREAD

**Issue by rob123king** [JBerthelier/PiRATE#17]
I have a shared drive setup but I can't get to it from the vm. All I want to do is access my data from the vm or transfer it to it. The tutorial is not working for me at this stage. Any more info on how to do this and change keyboard as I can get round launching galaxy but I can't find the $ key

**Comment by JBerthelier** [comment]
Dear Dr. King,
Thank you for your question.
Please let me know if this help you: https://github.com/JBerthelier/PiRATE/issues/7

Best regards,

Jérémy
