### ISSUE TITLE
TEannot - size genome

### ISSUE THREAD

**Issue by adriludwig** [JBerthelier/PiRATE#18]
Hello!
I am trying to use it in my studies and I have an important doubt in the TE annotation step. Is the genome size really in Mb as exemplified in the pipeline (85,000,000 Mb) or the correct is to use the size in bp? I tried to put the size in Mb but the statistical result did not make sense. 
Thanks a lot

**Comment by JBerthelier** [comment]
Dear adriludwig, 
Thank you for using PiRATE.
I am sorry for the delay of my answer.
Yes, there is a mistake for TEannot, the size is in bp. Thank you very much for this report. 
I am sorry for this waist of time for you. We will make change is the new version.

Please also be carreful to use the good format : 

Format your fasta file to have only 60 bps (or less) by line for each sequence. Concerning the sequence headers, it is highly advised to write them like this : ">XX_i" with XX standing for letters and i standing for numbers. Please, avoid space (" ") or symbols such as "=", ";", ":", "|"... 

Best regards

Jérémy

**Comment by adriludwig** [comment]
Thanks a lot!
Regards,
Adriana
