### ISSUE TITLE
use docker to make it more robust?

### ISSUE THREAD

**Issue by 444thLiao** [JBerthelier/PiRATE#19]
VM is a huge thing because of GUI.

Can it use docker to produce a virtual environment?

**Comment by JBerthelier** [comment]
Dear 444thLio, 

Thank you for your comments and sorry for my delay.
We are currently in the way to go into a docker. The work will be soon in process ;)

Best regards,

Jérémy

**Comment by sciroc** [comment]
Salut Jérémy,
what is the state of the Docker port? We (me and @timeu ) have a user who claims some applications inside PiRATE don't work. Plus, we have a virtualized HPC environment where we could run Docker containers "natively". I would appreciate any information regarding the state of affairs in this regard. Thanks in advance!
Best,
Felix

**Comment by JBerthelier** [comment]
Dear sciroc, 

PiRATE is no more my main project anymore. I am now working on other projects. 
I try to take time to improve PiRATE and help users when I have a bit of time.

My previous lab (Physiology and Biotechnology of Algae, Ifremer of Nantes), where I implemented PiRATE during my thesis, is also working on other projects. They also have few time to improve PiRATE.

What I know about the Docker port: 
Nothing have been done yet. The implementation is planned, and shoud be performed by an intership student during the begin of 2020. No idea when it will be ready to be publish. 
Do not wait for it. 

Best, 

Jeremy

**Comment by sciroc** [comment]
Thank you for your comment, Jérémy! The user did not get more specific than "not all the programs run". I will ask for more information and then open a new issue.
Best,
Felix
