### ISSUE TITLE
could not type correct letter in konsole

### ISSUE THREAD

**Issue by wangj2009** [JBerthelier/PiRATE#2]
1) During the process of installation, I could open the konsole, but could not type "sh /home/jeremy/galaxy/run.sh" correctly.
Actually it print "sh !ho,e!jere,y!gqlqxy!run:sh".
My platform is ubutu 14.04 LTS. And I installed the correct virtualbox and extension pack.
2) The menus of konsole is not in English, very hard to understand..

**Comment by JBerthelier** [comment]
Dear wangj2009, 

1. About the language, the PiRATE-VM has been firstly configured in French and then we changed the language setting in English. Unfortunately there is still some French word in some places... 

You can try to re-change the language setting by the following step: 
K menu -> setting system -> local --> Country/Region&Language --> (apply with English)

2. About  "sh !ho,e!jere,y!gqlqxy!run:sh"
The PiRATE-VirtualMachine has been configurate with an AZERTY Keypad, 
If you are using a QWERTY version (or other), please configure your keypad by following this steps:

K menu -> setting system -> input devices -> Keyboard
select "Layouts", check the box "Configure Layout", remove the actual setting, add your setting with the following:

Limit selection language: any language : any language
Disposition: Anglais (Royaume-Uni)
Variante: Default
Etiquette: gb
Raccourci: None

and apply

You can also see this tutorial video : 
https://www.youtube.com/watch?v=-878X2PT3BU

Please let me know if my explanations solved your problems,

Best,

Jérémy
