### ISSUE TITLE
PiRATE-VM

### ISSUE THREAD

**Issue by molecularwonder** [JBerthelier/PiRATE#20]
Hi,

I an not import the PiRATE-VM ova from the site into my virtual box. The PiRATE-VM file does not work. Could someone fix this.

thanks!

**Comment by JBerthelier** [comment]
Dear molecularwonder, 

Thank you for using PiRATE.

The ova file should work. 

Please check the PiRATE tutorial or the VirtualBox manual to properly import the ova file.

Best regards, 

Jeremy
