### ISSUE TITLE
Install PiRATE

### ISSUE THREAD

**Issue by Kyungkim-lab** [JBerthelier/PiRATE#21]
Hello,
I plan to install and use the PiRATE on VirtualBox in my laptop.
However, I cannot download the PiRATE-VM OVA file on my local folder.
When I clicked the PiRATE-VM, new window popped up with unknown scripts, which is not normal downloading I guess.
If you guide me how to download it, it would be appreciated.
Kyung

**Comment by JBerthelier** [comment]
Dear Kyungkim-lab,

Sorry I maybe missed your message, 
in case I didn't reply you by email: 
you can do click right on the "PiRATE-VM" link and select "save as"
Best regards, 

Jeremy
