### ISSUE TITLE
How to interpret the output of PASTEC in PiRATE

### ISSUE THREAD

**Issue by wangj2009** [JBerthelier/PiRATE#22]
Dear Jeremy,
PASTEC usually give consistent evidence of TE's superfamily, but we have these:
CI=27; coding=(TE_BLRtx: I-2_BM:ClassI:LINE:I: 5.09%, L2-13_DRe:ClassI:LINE:Jockey: 5.92%, L2_Plat1r:ClassI:LINE:Jockey: 6.23%, L2_Plat1u:ClassI:LINE:Jockey: 6.33%; TE_BLRx: L2-13_DRe_1p:ClassI:LINE:Jockey: 8.19%, L2-24_ACar_1p:ClassI:LINE:Jockey: 18.50%); struct=(TElength: <700bps); other=(SSRCoverage=0.12)
CI=27; coding=(TE_BLRtx: I-2_BM:ClassI:LINE:I: 7.61%; TE_BLRx: L2-18_ACar_1p:ClassI:LINE:Jockey: 19.78%, L2-29_ACar_2p:ClassI:LINE:Jockey: 20.92%, L2-9_DRe_1p:ClassI:LINE:Jockey: 22.64%); struct=(TElength: <700bps); other=(SSRCoverage=0.12)

  1) should we treat these contigs as LINE/I or LINE/Jockey? They are not potential chimeric but ok in the output.
   2) What's the meaning of TE_BLRtx and TE_BLRx? and the percentages mean similarity of divergency? Should we choose TE_BLRtx or TE_BLRx?
   3) Are the confidence index (CI) high or low? Is there a threshold to filter low quality annotation?
   4) Is the PASTEC output more accurate than those of RepeatMasker, which based on the similarity of 80-80-80 rule?

   Thank you very much and with best wishes,
Jie

**Comment by JBerthelier** [comment]
Dear wangj2009, 

1. in this case of study the TE have similarity to both Jockey and I. 
The best to do is to etheir to say that it it a LINE_undefined or etheir to manually find evidences to confirm if it is a I or a Jockey.

2-3. Please check the website and paper of the creator of PASTEC:
-  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4008368/
- https://urgi.versailles.inra.fr/Tools/PASTEClassifier/PASTEClassifier-tuto

TE_BLRtx -->  tBLASTx against the TE nucleic database of PiRATE
TE_BLRx --> BLASTx against the TE protein database of PiRATE

4. RepeatMasker is not a classifier, thus in my opignion PASTEC is fare more accurate.

Best regards, 

Jeremy
