### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by JDepot** [JBerthelier/PiRATE#33]
I am unable to have internet connection in the PiRATE-VM
I tried many network setting including Bridged Adapter, but nothing changes.

Can someone help me?

Many thanks in advance

**Comment by JBerthelier** [comment]
Dear JDepot, 

Sorry for my late answer, 
did you fix your internet problem ?
This is more a VirtualMachine related problem, than a PiRATE galaxy issue.
It is difficult to me to help you, this issue can be cause by several factors according to your system.

Please check VirtualBox manual or help threads. 

Best regards, 

Jeremy

**Comment by JDepot** [comment]
Dear Jeremy

Thank you for your answer.
I managed to fix my internet problem, but I encounter a problem with PASTEClassifier.
The log file seems to be stuck at waiting for x job(s). I tried it with a very large file and I tried it with a small file. 
I waited for days to no avail.

The fasta file I entered has only two entries
>QFA_6
TCGGCCTCAGATTGGTAGGACTACCCGCTGAACTTAAGCATATCAATAAGCGGAGGAAAA
GAAACTAACAAGGATTCCCCTAGTAACGGCGAGTGAAGAGGGAAGAGCCCAAGATTGAAA
GCTGGCGTCTTCGACGTCCGCATTGTAATCTCAAGAAGCGTTTTCCGCTTCGGACCATGC
CTAAGTCCCTTGGAAAAGGGCATCATAGAGGGTGATAATCCCGTACATGGCATGGAGCGC
CCGAAGCTTTGTGATACGTTTTCTAAGAGTCGAGTTGTTTGGGAATGCAGCTCAAAATGG
GTGGTAAATGCCATCTAAGGCTAAATATTGGGGAGAGACCGATAGCGAACAAGTACAGTG
ATGGAAAGATGAAAAGAACTTTGAAAAGAGAGTTAAACAGTACGTGAAATTGCCAAAAGG
GAAGGGTAGGAGGTCAGAGATGCGTCTTGGAATTCAGCCTTGCTTTTTGCTTGGTGTTTT
TTCCAAGTTTGCAGGCCAACGTCGGTTTTGGGCACTGGAGAAGGGTGGAAGGAACGTGGC
ACCCCTCGGGGTGTGTTATAGCCTTCCACTGGATACAGCGACCGAGACCGAGGACAGCAG
CGTACTCGCAAGAGCGGGCCCTCGGGCACCTTTACGCTTAGGGCGTTGGCATAATGGCCC
TCTACCACCCGTCTTGAAACACGGACCAAGGAGTCTAACATGTATGCGAGTCTTTGGGTG
GCAAACCCATAGGCGCAATGAAAGTGAATTCAGGTGGGATCCGCAAGGTGCACCATCGAC
CGATCCTCACGTCTTTTAAGTCGTGGATTTGAGTAAGAGCATACCTGTTGGGACCCGAAA
GATGGTGAACTATGCCTGAATAGGGTGAAGCCAGAGGAAACTCTGGTGGAGGCTCGTAGC
GGTTCTGACGTGCAAATCGATCGTCAAATTTGGGTATAGGGGCGAAAGACTAATCGAACC
ATCTAGTAGCTGGTTCCTGCCGAAGTTTCCCTCAGGATAGCAGAAACTCACATCAGTTTT
ATGAGGTAAAGCGAATGATTAGAGGCCTTGGGGAAGTAACTTCCTTAACCTATTCTCAAA
CTTTAAATGTGTAAGAAGCCCTTGTTACTTTAGTGAACGAGGGCATGCGAATGAGAGTTT
CTAGTGGGCCATTTTTGGTAAGCAGAACTGGCGATGCGGGATGAACCGAACGTTGGGTTA
AGGTGCCAAAGTATACGCTCATCAGATACCAGAAAAGGTGTTATTTAGTCTAGACAGTGG
GACGGTGGCCATGGAAGTCGGAAACCGCTAAGGAGTGTGTAACAACTCACCCACCGAATT
AAGTAGCCCTGAAAATGGATGGCGCTCAAGCGTATCACCGATACCCAACCGTCAGTGTTT
AGCGAAGCGCTGACGAGTAGGCAGGCGTGGGGGTCCGTATGGAAGCCTTGGCAGTGATGC
TGGGTGGAACGGCCTCTAGTGCAGATCTTGGTGGCAGTAGCAAATATTCAAGTGAGAACC
TTGAAGACTGAAGTGAGGAAAGGTTCCACGATTACAGCAATTGAACGTGGGTTAGCCGAT
CCTAAGAGATAGGGAAATTCCGTATTAAAGTTGTGCGCTTGTTCGCATCGACCTATCGAA
AGGGAAACAGGTTAAAATTCCTGTGCCGGGATGTGGATTTTTGGCGGCAACGCAAACAAA
CTAGGAGACGTCGGCGGAAGCCCTGGGGAGAGTTCTTTTCTTTTCTTAACGACACGACCC
ACCTCGGAATCAATTTACTTGGAGAAGGGGTAGGTCTGTCGGCAGAGCTAGGTACTTATG
CCTGGTCCGGAGCGCTTTCGACGACCCTTGAAAATCCTAGGGAGCGAATAATTTTCACAC
CCGGTCGTACTCATAACCGCATCAGGTCCTCAAGGTGAACAGCCTCTAGTTGATAGAATA
ATGTAGATAAGGGAAGTCGGCAAATTAGATCCGTAACTTCGGGATAAGGATTGGCTCTAA
GGGTTAGGTGGTTCGGGCCTTTGTTGGAAGCGACTGCTGGACCTGTCTGGACTGCTTTGG
GCAACTGAGGCGGACCGGACGGGACCGGCGGACGTGGAAGGCATGGGCAGCCTCGCGGCG
TCCTTTCCACAATTAATAACCAACTTAGAACTGGTACGGACAAGGGGAATCTGACTGTCT
AATTAAAACATAGCATTGCGATGGCCAGAAAGTGGTGTTGACGCAATGTGATTTCTGCCC
AGTGCTCTGAATGTCAAAGTGAAGAAATTCAACCAAGCGCGGGTAAACGGCGGGAGTAAC
TATGACTCTCTTAAGGTAGCCAAATGCCTCGTCATCTAATTAGTGACGCGCATGAATGGA
TTAACGAGATTCCCACTGTCCCTATCTACTATCTAGCGAAACCACAGCCAAGGGAACGGG
CTTGGCAAAATCAGCGGGGAAAGAAGACCCTGTTGAGCTTGACTCTAGTTTGACATTGTG
AAGAGACATGGAGGGTGTAGAATAAGTGGGAGCTTCTGCGCCGGTGAAATACCACTACCT
CCATCGTCTCTTTACTTATCCAATGAAGCGGAGCTGGGTTTAACGACCCACCTTTTGGAC
TTAAAAGCATTCATGCTTGATCCGAATTGGAGACATTGTCAGGTGGGGAGTTTGGCTGGG
GCGGCACATCTGTTAAACGATAACGCAGGTGTCCTAAGGGGGACTCATGGAGAACAGAAA
TCTCCAGTAGAACAAAAGGGTAAAAGTCCCCTTGATTTTGATTTTCAGTGTGAATACAAA
CCATGAAAGTGTGGCCTATCGATCCTTTAGATCCTCGGCATTTGAGGCTAGAGGTGCCAG
AAAAGTTACCACAGGGATAACTGGCTTGTGGCAGCCAAGCGTTCATAGCGACGTTGCTTT
TTGATCCTTCGATGTCGGCTCTTCCTATCATACCGAAGCAGAATTCGGTAAGCGTTGGAT
TGTTCACCCACTAATAGGGAACGTGAGCTGGGTTTAGACCGTCGTGAGACAGGTTAGTTT
TACCCTACTGATGGAGGGTTATCGTAACAGTAATTCAACTTAGTACGAGAGGAACTGTTG
ATTCGTGTAATTGGTCTTGGCCGTTGTCCAACAGGGCAGTGCGGCGAAGCTACCACACGC
TAGATAATGGCTGAACGCCTCTAAGCCAGAATCTGTGCTGGAAGCGATGATGTTGGTCCC
GCTTGTATGAAATGCGTAAAAATAAGGCATCTTCGGATGCTTGTGTACCATAGCTGGCGA
GGGACGGGCTGTTGGACGGAAAGGTCTGCGGTCTACCTCGTGAATTGCAATCACAATATG
AGCGGGGAAAAATCTCTTGCAGACGACTTGAATGGGAAGGGGGTGCTGTAAGCAGTAGAG
TGGCCTTGTTGCTACGATCTGCTGAGGCTCAGCCCTATCTTCCACGATTTGTTT
>QFA_8
TACCTGGTTGATTCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATGCATGTCT
AAGTATACGCAAATTATACTGTGAAACTGCGAATGGCTCATTAAATCAGTTATAGTTTAT
TTGATGTTTCTTGCTACATGGATAACTGTGGTAATTCTAGAGCTAATACATGCGTAAAAA
GCCCCGACTTCTGGAAGGGGTGTATTTATTAGATAAAAACCATCCTCCTCGGAGTTTGGT
GATTCATAATAACTTCTCGAATCGCACGGCCTTGTGCTGGCGATGCTTCATTCAAATATC
TGCCCTATCAACTGTCGATGGTAGGATAGAGGCCTACCATGGTTGCAACGGGTAACGGGG
AATAAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCCAAGGAAGGCA
GCAGGCGCGCAAATTACCCAATCCCGACACGGGGAGGTAGTGACAATAAATAACAATGCA
GGGCCCTTTTGGGTCTTGTAATTGGAATGAGTACAATTTAAATCCCTTAACGAGGAACGA
TTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCGTATATTAA
AGTTGTTGCAGTTAAAAAGCTCGTAGTTGAAGTTTGGTCTCGGACGCTGGGTCTGCTTAA
TTGCATGTACTTGACGGTCCGAGACTTCCTTCTTGGTGAACGGCCGCCTTCGGGTGGTCC
GGAACCAGGACTATTACTTTGAAAAAATTAGAGTGTTCAAAGCAGGCCATAGGCCCGAAT
ATATTAGCATGGAATAACAGAATAGGACGTGCGGTTCTATTTTGTTGGTTTCTAGAACTG
CCGTAATGATTAAAAGGGACAGCCGGGGGCATTAGTATTTGCACGCTAGAGGTGAAATTC
TTGGATTGTGCAAAGACTTCCTACTGCGAAAGCATTTGCCAAGAATGTTTTCATTAATCA
AGAACGAAGGTTAGGGTATCGAAAACGATTAGATACCGTTGTAGTCTTAACAGTAAACTA
TGCCGACTCCGAATCGGTCGATGCTCATTTCACTGGCTCGATCGGCGCGGTACGAGAAAT
CAAAGTTTTTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTAAAGAAATTGACG
GAAGGGCACCACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGAAAACTCAC
CGGGTCCGGACATAGTAAGGATTGACAGATTGATGGCGCTTTCATGATTCTATGGGTGGT
GGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGGTTAATTCCGATAACGAACGA
GACCTTGACCTGCTAAATAGACGGGTTGACATTTTGTTGGCCCCTTATGTCTTCTTAGAG
GGACAATCGACCGTCTAGGTGATGGAGGCAAAAGGCAATAACAGGTCTGTGATGCCCTTA
GATGTTCCGGGCTGCACGCGCGCTACACTGACAGAGACAACGAGTGGGGCCCCTTGTCCG
AAATGACTGGGTAAACTTGTGAAACTTTGTCGTGCTGGGGATGGAGCTTTGTAATTTTTG
CTCTTCAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGACTACGTCCCTG
CCCTTTGTACACACCGCCCGTCGCTACTACCGATTGAATGGCTTAGTGAGGACTTGGGAG
AGTACATCGGGGAGCCAGCAATGGCACCCTGACGGCTCAAACTCTTACAAACTTGGTCAT
TTAGAGGAAGTAAAAGTCGTAACAAGGTATCTGTAGGTGAACCTGCAGATGGATCATT

**Comment by JBerthelier** [comment]
Dear JDepot, 

If the fasta file that you are showing me is the same than the one you are using:
the  ">" at the beging of the headers of the both sequences are missing.

If not, can you run again PASTEC with those both sequences, and send me 

- the log file 
- the error expressed by galaxy

, this will help me to identificate the error cause.

**Comment by JDepot** [comment]
Dear Jeremy

Thank you for your reply.
Indeed I forgot to paste the ">", but they were in my original file.
When I run PASTEC I do not get an error message, but the program runs for days (even though there are only two sequences).
The log file looks like this:
2020-04-09 11:30:40 - PASTEClassifier - INFO - START PASTEClassifier
parallelized
2020-04-09 11:30:40 - PASTEClassifier - INFO - Fasta file name: genome.fa
2020-04-09 11:30:40 - PASTEClassifier - INFO - Running STEP 1 of
PASTEClassifier parallelized: DetectTEFeatures
START DetectTEFeatures_parallelized
Fasta file name: genome.fa
split the sequences in batches Homogeneous in size 20kbp
launch the programs on each batch
prepare bank 'PiRATE_nucl.fa'...
prepare bank 'PiRATE_prot.fa'...
prepare bank 'Pfam27.0_GypsyDB_PiRATE_hmmer.hmm'...
submitting job(s) with groupid 'genome_detectTEFeaturesParallelized'
(2020-04-09 11:32:11)
waiting for 1 job(s) with groupid
'genome_detectTEFeaturesParallelized' (2020-04-09 11:32:11)

Thanks in advance

**Comment by JBerthelier** [comment]
Indeed, with two sequences PASTEC should not take lot of time. 

How much ram and core did you configure in the VM ?

Moreover, can you try to launch PASTEC again. Look the log file, and when the message "waiting for 1 job(s) with groupid
'genome_detectTEFeaturesParallelized' "
 appear, open a new konsol and use "qstat" , you should see the pastec job running

The state of the job, should be "r" (running).

Is it the case ?
