### ISSUE TITLE
Unable to upload data from my Local PC. 

### ISSUE THREAD

**Issue by majie5976** [JBerthelier/PiRATE#35]
Hi Dear @JBerthelier ,
I just successfully installed PiRATE, But the problem I'm facing right now related to uploading data from my Local device. Whenever I selected "choose local file" option it always directed to your directory instead of mine local PC. Because I haven't used this platform before, Could you please help me to resolve this issue.
Many Thanks!
![PiRATE](https://user-images.githubusercontent.com/54849045/84217198-16d9a980-aafe-11ea-8e84-94e41117ce4c.JPG)

**Comment by JBerthelier** [comment]
Dear majie5976,

Please check the differents way in these previous "issues pages":

 https://github.com/JBerthelier/PiRATE/issues/14

&

https://github.com/JBerthelier/PiRATE/issues/28


Basically you have to transfert your data from the local computer to the virtual machine.

Best regards, 

Jeremy

**Comment by majie5976** [comment]
Hi @JBerthelier ,
Thanks a lot, it worked.
