### ISSUE TITLE
hmmer error/bug

### ISSUE THREAD

**Issue by Shellfishgene** [JBerthelier/PiRATE#4]
Hi, 
running PiRATE I just came across this [hmmer bug](https://github.com/EddyRivasLab/hmmer/issues/135) when running TE-HMMER. It is fixed in newer versions of hmmer, I so updated hmmer on the VM. I did not try TE-HMMER with the new version yet, but if it works maybe you could include an updated hmmer in the VM.

**Comment by Shellfishgene** [comment]
Tried it now, the same dataset finished without errors with the current HMMERbversion 3.2.1.

**Comment by JBerthelier** [comment]
Hi, 
Thank you for having pointed and fixed this error !
We are working on the new version of PiRATE and we will apply your proposed changes.
Best,
