### ISSUE TITLE
PiRATE DEFAULT DATABANKS

### ISSUE THREAD

**Issue by Lukanyo12** [JBerthelier/PiRATE#40]
Hello @ Jérémy Berthelier
Does nucleotide and protein default databanks of PiRATE include all the sequences from Repbase Update, I am planning to do a comprehensive genome-wide TE analysis in my study. Thank you in advance!

**Comment by Lukanyo12** [comment]
Also, for RepeatExplore step. What if someone already has paired-end reads....FASTQ files. Does these mean I cannot use them for dnaPipeTE and RepArk tools? Reason being that I only paired-end read data.

**Comment by JBerthelier** [comment]
Dear Lukanyo12, 

It include repbase REPET version 20.05 (as indicated on the paper), no update since.

For RepeatExplorer/RepArk, you have to convert your fastq file into fasta file. Please check in the tuto.
There is also several ways to do it via linux command.

Best regards, 

Jeremy
