### ISSUE TITLE
Run PiRATE without using Illumina raw data

### ISSUE THREAD

**Issue by Lukanyo12** [JBerthelier/PiRATE#45]
Hello, I wondering if it is possible to run PiRATE using genome assemblies only? I only have PacBio long read sequencing data, hence I cannot use those tools such as RepArch since they require an Illumina raw data

**Comment by JBerthelier** [comment]
Dear Lukanyo12, 

Yes, there is no problem for that, you can employ only the tools that use the genome assembly (detection approches 1, 2 and 3).
On the PiRATE-Galaxy, the tools have to be launch one by one, thus you can select those you want to use.

This will give you a library of TE sequence to annotate the genome assembly.

Best, 

Jeremy
