### ISSUE TITLE
TEannot query

### ISSUE THREAD

**Issue by pwkooij** [JBerthelier/PiRATE#46]
Hi

I have a quick question regarding TEannot. I just did the first run, but in the tutorial you do a second run. Which of the output files from the first run do you use for this?
- Full length copy
- Full length fragment
- TE with one copy and more

Cheers
Pepijn

**Comment by JBerthelier** [comment]
Dear Pepijn,

The author of REPET (TEdenovo, PASTEC, TEannot) advised me to do a second run with the Full length copy (FLC).

The sequences in the Full length copy, become your final TE library for the TEannotation. 
This helps to reduce the redundancy of the reference TE sequences.

Cheers, 

Jeremy

**Comment by pwkooij** [comment]
ok, thanks for the answer, Jeremy, much appreciated!

**Comment by Lukanyo12** [comment]
Hello @ JBerthelier, is there any script for removal of redundancy
sequences in CD Hit_est, or we are expected to eliminate the redundant
sequences our selves after the run/clustering

Best
Lukanyo
