### ISSUE TITLE
TE content (%)

### ISSUE THREAD

**Issue by Lukanyo12** [JBerthelier/PiRATE#50]
Hello Jeremy,

As I have decided to use a single TEs library ( library excludes unknown repeats from PASTEC classification) for TEannot step. How can I determine the content of TEs in my genome e.g Class I, class II, and total TE content. For unknown repeats also, how can I determine their proportion in the genome?
From PASTEC output, I decided that I will separate the elements as Class I, Class II and unknown repeats. Howver, unknown repeats will be separated from the TE library that will be used for TE annot step.
Best regards
Lukanyo

**Comment by JBerthelier** [comment]
Dear Drsurch13, 

Yes sure this is the best way to do. This gonna help you to highlight potential false positives identified by sine-finder /  mite-hunter.

Best

Jeremy
