### ISSUE TITLE
PASTEC Classification

### ISSUE THREAD

**Issue by Lukanyo12** [JBerthelier/PiRATE#52]
Hello Jeremy
Is it possible for class II TIR to be detected by LTR harvest, and MITE to be detected by SINE finder. I have TE which have be detected by LTR harvest, and SINE -finder but I found some few sequences classified as Class II TIR or MITE while dected by LTR or SINE.

Thank you
Lukanyo

**Comment by JBerthelier** [comment]
Dear Lukanyo, 

Yes, this can happen to have this kind of weird predictions.  
I would sugest to considere them as false positives and do not take them for the final library.

Best, 

Jeremy
