### ISSUE TITLE
MCL

### ISSUE THREAD

**Issue by Lukanyo12** [JBerthelier/PiRATE#55]
Hello Jeremy, I am trying to cluster TEs sequences of the order Crypton into predicted TE families using MCL. Both sequences were classified as potential chimeric according to information from PASTEC ( The Crypton order is only composed of two sequences  that were detected and classified as potential chimeric). 
Error message: Fatal error : Exit code 1 ()
Can't open genome _MCL.fa :  Aucun fichier ou dossier de ce type.
cp: impossible d' evaluer <<genome _MCL.fa:Aucun fichier ou dossier de ce type

Your advice would be highly appreciated
Best wishes 
Lukanyo

**Comment by JBerthelier** [comment]
Does MCL works with other TE Order? 

Maybe you get this error because you submit only two sequences that are very divergentes (False positives) ?

Best 

Jeremy

**Comment by Lukanyo12** [comment]
Yes MCL worked in all other TE orders except this one. Maybe that is the case. Thank you so much for your response!
