### ISSUE TITLE
PiRATE availability

### ISSUE THREAD

**Issue by DEsalasL** [JBerthelier/PiRATE#6]
Hi there, I was wondering ... is there a way to get the software not as virtual machine? I ask this as the VM won't work with our cluster.

**Comment by JBerthelier** [comment]
Hi, 

PiRATE is more like a pipeline/platform composed a numerous existing softwares to identify/classify/annotate TEs. 
See: https://pag.confex.com/pag/xxvi/recordingredirect.cgi/oid/Recording3168/paper29148_1.pdf 

Every softwares are available online by their own designer and can be download. 

The advantage of PiRATE is that every softwares are already installed in the VM are automatized in a standalone Galaxy. 

I would be also interesting about using PiRATE with a cluster but I am not familiar with those system. 

I found this https://csinparallel.org/csinparallel/vm_cluster_macalester.html 

Maybe it can help ? Let me now if you try ... 

You can also use PiRATE on a basic computer. 

Best, 

Jérémy 


----- Mail original -----

De: "DEsalasL" <notifications@github.com> 
À: "JBerthelier/PiRATE" <PiRATE@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Vendredi 28 Septembre 2018 17:34:10 
Objet: [JBerthelier/PiRATE] PiRATE availability (#6) 



Hi there, I was wondering ... is there a way to get the software not as virtual machine? I ask this as the VM won't work with our cluster.
