### ISSUE TITLE
How to import raw illumina files 

### ISSUE THREAD

**Issue by jpicathartes** [JBerthelier/PiRATE#7]
Hello--

I am having a hard time figuring out how to upload my raw illumina files (located on the desktop of the local computer). The manual suggests to "copy and paste" the files to "administrator@pba.fr", but I am not quite sure how to do this. Clicking and dragging my files from the desktop to this location doesn't seem to be working. 

Any help or clarification would be greatly appreciated. 

Many thanks
Jack

**Comment by JBerthelier** [comment]
Dear Jack, 

I have answered to your question on Github, 

in complement you will find a update (but not finished ) version of the manual, 

I hope this will help you 

If you have time, 

I would be interested to know what species are you studying and what data will you used. 

Best, 

Jérémy 





----- Mail original -----

De: "Jack Hruska" <notifications@github.com> 
À: "JBerthelier/PiRATE" <PiRATE@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mercredi 3 Octobre 2018 20:50:05 
Objet: [JBerthelier/PiRATE] How to import raw illumina files (#7) 



Hello-- 

I am having a hard time figuring out how to upload my raw illumina files (located on the desktop of the local computer). The manual suggests to "copy and paste" the files to " administrator@pba.fr ", but I am not quite sure how to do this. Clicking and dragging my files from the desktop to this location doesn't seem to be working. 

Any help or clarification would be greatly appreciated. 

Many thanks 
Jack

**Comment by JBerthelier** [comment]
Dear Jack, 

I attached the manual in my previous email, 

let me know if it doesn't work, 

Thanks for the information, this a nice species to studied ! 

Best, 

Jérémy 

----- Mail original -----

De: "Jack Hruska" <notifications@github.com> 
À: "JBerthelier/PiRATE" <PiRATE@noreply.github.com> 
Cc: "Jérémy Berthelier" <berthelier.j@laposte.net>, "State change" <state_change@noreply.github.com> 
Envoyé: Jeudi 4 Octobre 2018 16:22:23 
Objet: Re: [JBerthelier/PiRATE] How to import raw illumina files (#7) 



Hi Jeremy-- 

Many thanks for the quick reply. My apologies if this is a silly question, but where can I find an updated version of the manual? 

I'll be working on a genome of a woodpecker, Colaptes, that was assembled using PacBio (long-read) data. 

Best 
Jack

**Comment by jpicathartes** [comment]
Hi Jeremy--

Unfortunately, I did not receive an attachment along with the email. Would you mind sending it again?

Many thanks
Jack

**Comment by JBerthelier** [comment]
Hi OK, can you give me your emailMy email is berthelier.j@laposte.netThanks,Jeremy

**Comment by jpicathartes** [comment]
Hi Jeremy--

My email is jph239@cornell.edu

Best
Jack

**Comment by pwkooij** [comment]
I have tried to connect to the VM using FTP, but I can't seem to get it to work. Do you have any instructions?

**Comment by JBerthelier** [comment]
Dear pwkooij, 

1)Firsly check your Network Configuration in VirtualBox for the PiRATE-VM

Select Global Settings from the File menu --> Select the Network item in the list
-In "attached to" check that the "Bridged Network" is selected
-Go in "advanced" (blue arrow)
-Check that for the Promiscuous mode  "Allow All"

2) Start your PiRATE-VM

**1-just in case restart the proftdp:**

open a konsol and run:
sudo /etc/init.d/proftpd reload  
sudo /etc/init.d/proftpd restart

**2-Obtain your ip adree**
open a konsol and run the **ifconfig** command (https://www.computerhope.com/unix/uifconfi.htm)

Example:

eth0      Link encap:Ethernet  HWaddr 09:00:12:90:e3:e5  
          **inet addr:192.168.1.29** Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe70:e3f5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:54071 errors:1 dropped:0 overruns:0 frame:0
          TX packets:48515 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:22009423 (20.9 MiB)  TX bytes:25690847 (24.5 MiB)

this will show you the  "inet adr:"  which is your ip adress

Then  go back to your physical machine

Open Filezilla and connect you to the PiRATE-VM

Host: **YOURIPadress**    login: **jeremy**    password: **jeremy07**  Port: **21**

I just re-checked this method this morning and it works for me, 

Best!

Jeremy
